name: CLIG
url: https://cligr.github.io/

exclude: [bibble, README.md, Makefile, Dockerfile]

# use this library to parse Markdown
# markdown: redcarpet
# redcarpet:
#     extensions: [smart, tables, with_toc_data, strikethrough]

# colorize code snippets with the pygment module
highlighter: rouge

# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html

# Sections on the "people" page.
roles:

    - {key: ugrad, name: Undergrad Students}
    - {key: teacher, name: K-12 Educators}
    # - {key: vscholar, name: Visiting Scholars}
    - {key: collab, name: Collaborators}
    # - {key: postdoc, name: Researchers}
    - {key: grad, name: Graduate Students}
    - {key: faculty, name: Faculty}
    # - {key: ugrad-alum, name: Past Undergraduate Students}
    - {key: alum, name: Alumni}

# Number of news stories on the front page.
front_page_news: 5

# Base pathname for links.
base: ''

collections:
  projects:
    output: true

# Navigation bar links.
navigation:
    - title: Home
      link: /
    - title: Research
      link: /research/
    # - title: Publications
    #   link: /publications.html
    - title: Events
      link: /events.html
    - title: Code
      link: /code.html


# Rewriting of old path names.
wiki_redirects:
    People: people.html
    Projects: research/
    Publications: publications.html
    Funding: ''
    Main_Page: ''

# Convenient short-URL redirects.
short_urls:
    decaf: research/approximation/decaf/
